#! /usr/bin/env ruby

require 'pg'

CONNECTION = PG.connect(dbname: "expense_db")

def display_help
  help_content = <<~HEREDOC
  An expense recording system

  Commands:
  
  add AMOUNT MEMO [DATE] - record a new expense
  clear - delete all expenses
  list - list all expenses
  delete NUMBER - remove expense with id NUMBER
  search QUERY - list expenses with a matching memo field

  HEREDOC

  puts(help_content)
end

def list_expenses
  result = CONNECTION.exec("SELECT * FROM expenses ORDER BY created_on ASC;")

  result.each do |tuple|
    columns = [ tuple["id"].rjust(3),
                tuple["created_on"].rjust(10),
                tuple["amount"].rjust(12),
                tuple["memo"]]
    puts columns.join(" | ")
  end
end

def add_expense(amount, memo)
  sql = "INSERT INTO expenses (amount, memo) VALUES ($1, $2);"
  CONNECTION.exec_params(sql, [amount, memo])
end



command_arg = ARGV.first

if command_arg == "list"
  list_expenses
elsif command_arg == "add"
  amount = ARGV[1]
  memo = ARGV[2]
  abort("You must provide an amount and memo") unless amount && memo
  add_expense(amount, memo)
else 
  display_help
end


